# Generated by Django 2.2.9 on 2020-04-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200402_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contest_rang',
            field=models.CharField(choices=[('Новичек', 'Новичек'), ('Лиманадек', 'Лиманадек'), ('Черниговский батон', 'Черниговский батон'), ('Сыр косичка', 'Сыр косичка'), ('Масленок', 'Масленок'), ('Простой советский forik', 'Простой советский forik'), ('Живой огурец', 'Живой огурец'), ('Мафиозник', 'Мафиозник'), ('Олимпиадник', 'Олимпиадник'), ('Sempai', 'Sempai'), ('Sensei', 'Sensei'), ('Галактический кодер', 'Галактический кодер')], default='Новичек', max_length=45),
        ),
    ]
