# Generated by Django 2.2.9 on 2020-04-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200413_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contest_rating',
            field=models.IntegerField(default=0),
        ),
    ]
