# Generated by Django 2.2.9 on 2020-04-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200415_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contest_rang',
            field=models.CharField(choices=[('Новичек', 'Новичек'), ('Лиманадек', 'Лиманадек'), ('Черниговский батон', 'Черниговский батон'), ('Сыр косичка', 'Сыр косичка'), ('Масленок', 'Масленок'), ("Советский for'ик", "Советский for'ик"), ('Живой огурец', 'Живой огурец'), ('Мафиозник', 'Мафиозник'), ('Олимпиадник', 'Олимпиадник'), ('Sensei', 'Sensei'), ('Галактический кодер', 'Галактический кодер')], default='Новичек', max_length=45),
        ),
    ]
