# Generated by Django 2.2.9 on 2020-04-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200415_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='instructor',
            field=models.BooleanField(default=False),
        ),
    ]
