# Generated by Django 2.2.9 on 2020-04-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_userprofile_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contest_rang_color',
            field=models.CharField(choices=[('AAAAAA', 'AAAAAA'), ('6F72BE', '6F72BE'), ('7F9ED8', '7F9ED8'), ('7FBAD8', '7FBAD8'), ('88F8FF', '88F8FF'), ('00FFC5', '00FFC5'), ('1EFF88', '1EFF88'), ('F0FF00', 'F0FF00'), ('FFA600', 'FFA600'), ('FF6100', 'FF6100'), ('FF0000', 'FF0000')], default='AAAAAA', max_length=10),
        ),
    ]
