# Generated by Django 2.2.9 on 2020-04-25 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200425_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-contest_rating']},
        ),
    ]
