# Generated by Django 2.2.9 on 2020-04-06 14:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('duration', models.DateTimeField(default=datetime.timedelta(seconds=7200))),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ContestTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('time_limit', models.PositiveIntegerField(default=1)),
                ('memory_limit', models.PositiveIntegerField()),
                ('solution', models.FileField(upload_to='code_files/')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='contest.Contest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
