# Generated by Django 2.2.9 on 2020-04-06 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='start_time',
            new_name='starts_at',
        ),
    ]
