# Generated by Django 2.2.9 on 2020-04-06 15:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200402_2104'),
        ('contest', '0002_auto_20200406_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty', models.IntegerField(default=0)),
                ('task_solved', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-task_solved', 'penalty'),
            },
        ),
        migrations.AddField(
            model_name='contest',
            name='problem_set_size',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contesttask',
            name='difficulty',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('b1', 'B1'), ('b2', 'B2'), ('c', 'C'), ('c1', 'C1'), ('c2', 'C2'), ('d', 'D'), ('d1', 'D1'), ('d2', 'D2'), ('e', 'E'), ('e1', 'E1'), ('e2', 'E2'), ('f', 'F'), ('f1', 'F1'), ('f2', 'F2'), ('g', 'G'), ('h', 'H'), ('i', 'I'), ('j', 'J'), ('k', 'K'), ('l', 'L')], default='a', max_length=3),
        ),
        migrations.CreateModel(
            name='ContestSolutionCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('task_file', models.FileField(upload_to='code_files/')),
                ('verdict', models.CharField(default='Выполняется проверка', max_length=150)),
                ('solved', models.BooleanField(default=False)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='contest.ContestParticipant')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='contest.ContestTask')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contestparticipant',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='contest.Contest'),
        ),
        migrations.AddField(
            model_name='contestparticipant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile'),
        ),
    ]
