# Generated by Django 2.2.9 on 2020-04-07 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20200407_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestparticipant',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='contestparticipant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='contestsolutioncase',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='contestsolutioncase',
            name='task',
        ),
        migrations.RemoveField(
            model_name='contesttask',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='contesttest',
            name='task',
        ),
        migrations.DeleteModel(
            name='Contest',
        ),
        migrations.DeleteModel(
            name='ContestParticipant',
        ),
        migrations.DeleteModel(
            name='ContestSolutionCase',
        ),
        migrations.DeleteModel(
            name='ContestTask',
        ),
        migrations.DeleteModel(
            name='ContestTest',
        ),
    ]
