# Generated by Django 2.2.9 on 2020-04-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_contest_contestparticipant_contestsolutioncase_contesttask_contesttest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='duration',
        ),
        migrations.AddField(
            model_name='contest',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=120),
        ),
    ]
