# Generated by Django 2.2.9 on 2020-04-08 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_auto_20200407_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestparticipant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='account.UserProfile'),
        ),
    ]
