# Generated by Django 2.2.9 on 2020-04-08 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_auto_20200408_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestsolutioncase',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='contest.ContestParticipant'),
        ),
        migrations.AlterField(
            model_name='contestsolutioncase',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='contest.ContestTask'),
        ),
    ]
