# Generated by Django 2.2.9 on 2020-04-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0011_auto_20200409_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='contesttask',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
