# Generated by Django 2.2.9 on 2020-04-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0015_auto_20200409_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestsolutioncase',
            name='language',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
