# Generated by Django 2.2.9 on 2020-04-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0016_contestsolutioncase_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestsolutioncase',
            name='task_code',
            field=models.TextField(default='<Code>'),
        ),
    ]
