# Generated by Django 2.2.9 on 2020-04-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0019_auto_20200411_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contesttest',
            name='answer',
            field=models.TextField(blank=True, default=None),
        ),
    ]
