# Generated by Django 2.2.9 on 2020-04-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0020_auto_20200411_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='contesttest',
            name='judge_answer',
            field=models.CharField(blank=True, max_length=1000000),
        ),
    ]
