# Generated by Django 2.2.9 on 2020-04-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0021_contesttest_judge_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contesttest',
            name='judge_answer',
        ),
    ]
