# Generated by Django 2.2.9 on 2020-04-13 20:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0023_contesttask_solved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestparticipant',
            name='stats',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, size=16),
        ),
    ]
