# Generated by Django 2.2.9 on 2020-04-14 05:32

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0024_auto_20200413_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestPastParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveIntegerField()),
                ('user', models.CharField(max_length=50)),
                ('penalty', models.PositiveIntegerField()),
                ('stats', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=16)),
                ('tasks_solved', models.IntegerField(default=0)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_participants', to='contest.Contest')),
            ],
            options={
                'ordering': ('-tasks_solved', 'penalty'),
            },
        ),
    ]
