# Generated by Django 2.2.9 on 2020-04-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0028_contestparticipant_u'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestparticipant',
            name='u',
        ),
        migrations.RemoveField(
            model_name='contestparticipant',
            name='username',
        ),
        migrations.AddField(
            model_name='contestparticipant',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
