# Generated by Django 2.2.9 on 2020-04-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0031_auto_20200424_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestpastparticipant',
            name='contest_rang_color',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
