# Generated by Django 2.2.9 on 2020-04-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0034_contesttask_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='contesttask',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
