# Generated by Django 2.2.9 on 2020-05-01 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0036_auto_20200501_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contesttest',
            options={'ordering': ['created']},
        ),
    ]
