# Generated by Django 2.2.9 on 2020-05-01 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0037_auto_20200501_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contesttask',
            options={'ordering': ['order']},
        ),
    ]
