# Generated by Django 3.0.6 on 2020-05-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0038_auto_20200501_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestsolutioncase',
            name='verdict',
            field=models.CharField(default='Ожидается проверка', max_length=150),
        ),
    ]
