# Generated by Django 2.2.9 on 2020-04-24 18:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0010_userprofile_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('time_limit', models.PositiveIntegerField(default=1)),
                ('memory_limit', models.PositiveIntegerField()),
                ('solved_by', models.IntegerField(default=0)),
                ('solution', models.FileField(upload_to='code_files/')),
                ('difficulty', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('b1', 'B1'), ('b2', 'B2'), ('c', 'C'), ('c1', 'C1'), ('c2', 'C2'), ('d', 'D'), ('d1', 'D1'), ('d2', 'D2'), ('e', 'E'), ('e1', 'E1'), ('e2', 'E2'), ('f', 'F'), ('f1', 'F1'), ('f2', 'F2'), ('g', 'G'), ('h', 'H'), ('i', 'I'), ('j', 'J'), ('k', 'K'), ('l', 'L'), ('', '')], default='a', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('answer', models.TextField(blank=True, default=None)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='education.CourseTask')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseSolutionCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('language', models.CharField(blank=True, max_length=30)),
                ('task_file', models.FileField(upload_to='code_files/')),
                ('task_code', models.TextField(default='#include <cheats>\nusing namespace hack;\nint main () {\nchar input[];\ncin >> input;\ncout << hack::get_solution(input);\nreturn 0;\n}')),
                ('verdict', models.CharField(default='Выполняется проверка', max_length=150)),
                ('solved', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_packages', to='education.CourseTask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_packages', to='account.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
