# Generated by Django 2.2.9 on 2020-04-16 18:52

from django.db import migrations
import management.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200416_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=management.fields.OrderField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=management.fields.OrderField(blank=True, default=True),
        ),
    ]
