# Generated by Django 2.2.9 on 2020-04-16 19:02

from django.db import migrations
import management.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200416_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='order',
            field=management.fields.OrderField(blank=True, default=0),
        ),
    ]
