# Generated by Django 2.2.9 on 2020-04-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_userprofile_instructor'),
        ('courses', '0005_auto_20200416_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses', to='account.UserProfile'),
        ),
    ]
