# Generated by Django 2.2.9 on 2020-04-21 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20200421_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={},
        ),
        migrations.RemoveField(
            model_name='content',
            name='order',
        ),
    ]
