# Generated by Django 2.2.9 on 2020-04-24 22:35

from django.db import migrations
import management.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20200425_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='order',
            field=management.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TaskTest',
        ),
    ]
