# Generated by Django 3.0.6 on 2020-05-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20200507_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='item_title',
            field=models.CharField(max_length=300, verbose_name='Название объекта. (Не отображается на странице модуля)'),
        ),
        migrations.AlterField(
            model_name='file',
            name='item_title',
            field=models.CharField(max_length=300, verbose_name='Название объекта. (Не отображается на странице модуля)'),
        ),
        migrations.AlterField(
            model_name='image',
            name='item_title',
            field=models.CharField(max_length=300, verbose_name='Название объекта. (Не отображается на странице модуля)'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, verbose_name='Краткое описание модуля'),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Название модуля'),
        ),
        migrations.AlterField(
            model_name='text',
            name='item_title',
            field=models.CharField(max_length=300, verbose_name='Название объекта. (Не отображается на странице модуля)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='item_title',
            field=models.CharField(max_length=300, verbose_name='Название объекта. (Не отображается на странице модуля)'),
        ),
    ]
