# Generated by Django 2.2.9 on 2020-04-13 14:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200413_1640'),
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('answer', models.TextField(blank=True, default=None)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='archive.ArchiveTask')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArchiveSolutionCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('language', models.CharField(blank=True, max_length=30)),
                ('task_file', models.FileField(upload_to='code_files/')),
                ('task_code', models.TextField(default='#include <cheats>\nusing namespace hack;\nint main () {\nchar input[];\ncin >> input;\ncout << hack::get_solution(input);\nreturn 0;\n}')),
                ('verdict', models.CharField(default='Выполняется проверка', max_length=150)),
                ('solved', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='archive.ArchiveTask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='account.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
