# Generated by Django 2.2.9 on 2020-04-13 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_archivesolutioncase_archivetest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivesolutioncase',
            options={'ordering': ('-package_time',)},
        ),
    ]
