# Generated by Django 3.0.6 on 2020-05-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_auto_20200424_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivetask',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
