# Generated by Django 3.0.6 on 2020-05-07 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_archivetask_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivetest',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='archivetest',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
